INVALID_BODY = 'Invalid body data type'
INVALID_ID_TYPE = 'Invalid ID type'
INVALID_KEYS_FOR_UPDATE = 'Invalid keys for update'
USER_NOT_FOUND = 'User not found'
INVALIDA_DATA_FOR_CHANGE_PASSWORD = 'Invalid data for change password'
PASSWORD_DOESNOT_MATCH = 'Password does not match'