USER_EXISTS = 'uncorrect email/password'
USER_NOT_FOUND = 'user not found'
USER_PASSWORD_WRONG = USER_EXISTS
USER_WRONG_REFRESH_TOKEN = USER_EXISTS
UNCORECT_TYPE_REFRESH_TOKEN = 'uncorrect type of refresh token'
UNCORECT_TYPE_EMAIL_PASSWORD = USER_EXISTS
