"""add many-to-many favourite user movie

Revision ID: ad2ab2e6b278
Revises: 4d6cecf1f7f0
Create Date: 2022-12-22 19:37:38.525307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad2ab2e6b278'
down_revision = '4d6cecf1f7f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite_user_movies',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_favourite_user_movies_movie_id_movies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favourite_user_movies_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'movie_id', name=op.f('pk_favourite_user_movies'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourite_user_movies')
    # ### end Alembic commands ###
